INSERT INTO GENRES (ID, NAME) VALUES (1, "Novel");
INSERT INTO GENRES (ID, NAME) VALUES (2, "Technical literature");

INSERT INTO AUTHORS (ID, NAME, SURNAME) VALUES (1, "Leo", "Tolstoy");
INSERT INTO AUTHORS (ID, NAME, SURNAME) VALUES (2, "Brian", "Goetz");
INSERT INTO AUTHORS (ID, NAME, SURNAME) VALUES (3, "Joshua", "Bloch");

INSERT INTO BOOKS (ID, TITLE, ISBN, GENRE_ID) VALUES (1, "War and Peace", "978-1-85326-062-9", 1);
INSERT INTO BOOKS (ID, TITLE, ISBN, GENRE_ID) VALUES (2, "Java Concurrency in Practice", "0321349601", 2);

INSERT INTO BOOK_AUTHORS (BOOK_ID, AUTHOR_ID) VALUES (1, 1);
INSERT INTO BOOK_AUTHORS (BOOK_ID, AUTHOR_ID) VALUES (2, 2);
INSERT INTO BOOK_AUTHORS (BOOK_ID, AUTHOR_ID) VALUES (2, 3);