DROP TABLE IF EXISTS AUTHORS;
DROP TABLE IF EXISTS BOOKS;
DROP TABLE IF EXISTS GENRES;
DROP TABLE IF EXISTS BOOK_AUTHORS;

CREATE TABLE AUTHORS(
    ID INT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    SURNAME VARCHAR(255) NOT NULL
);

CREATE TABLE BOOKS(
    ID INT PRIMARY KEY,
    TITLE VARCHAR(255),
    ISBN VARCHAR(255),
    GENRE_ID INT,
    FOREIGN KEY (GENRE_ID) REFERENCES GENRES(ID)
);

CREATE TABLE BOOK_AUTHORS(
    BOOK_ID INT,
    AUTHOR_ID INT,
    FOREIGN KEY (BOOK_ID) REFERENCES BOOKS(ID),
    FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS(ID)
);

CREATE TABLE GENRES(
    ID INT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL
);
